"""empty message

Revision ID: 452f77186f67
Revises: 1c84074536f4
Create Date: 2024-12-18 11:40:37.787235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452f77186f67'
down_revision = '1c84074536f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('users_password_key', type_='unique')
        batch_op.create_unique_constraint(None, ['password_hash'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_password_key', ['password'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
