"""initial version

Revision ID: 69314185a133
Revises: 98cebd50ae98
Create Date: 2024-12-18 14:45:41.368550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69314185a133'
down_revision = '98cebd50ae98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workoutplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('workoutplan_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['workoutplan_id'], ['workoutplan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    op.drop_table('workoutplan')
    op.drop_table('users')
    # ### end Alembic commands ###
