"""add relationship between workoutplan and exercise

Revision ID: 98cebd50ae98
Revises: 1a7e4c472541
Create Date: 2024-12-18 14:38:25.069882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cebd50ae98'
down_revision = '1a7e4c472541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workoutplan_exercise')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workoutplan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'workoutplan', ['workoutplan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workoutplan_id')

    op.create_table('workoutplan_exercise',
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='workoutplan_exercise_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['workout_id'], ['workoutplan.id'], name='workoutplan_exercise_workout_id_fkey')
    )
    # ### end Alembic commands ###
