"""users table

Revision ID: dc2c07daa8b1
Revises: 
Create Date: 2024-12-18 10:49:11.580752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc2c07daa8b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
        batch_op.drop_constraint('exercise_category_key', type_='unique')
        batch_op.drop_constraint('exercise_description_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('workoutplan', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
        batch_op.drop_constraint('workoutplan_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutplan', schema=None) as batch_op:
        batch_op.create_unique_constraint('workoutplan_description_key', ['description'])
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_unique_constraint('exercise_description_key', ['description'])
        batch_op.create_unique_constraint('exercise_category_key', ['category'])
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('password', name='user_password_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
